version: '2'
services:
  deploy:
    build:
      context: .
      dockerfile: app.Dockerfile
    expose: [ "8080" ]
    ports: [ "8080:8080" ]
    volumes: 
      - /home/student/workspace/spring_boot_job/docker-2/build/libs:/opt/
